name: 🚀 Terraform Deploy
on:
  workflow_call:
    inputs:
      branch:
        description: The Terraform branch to deploy
        type: string
        required: true
      aws-account:
        description: The AWS account to deploy to
        type: string
        required: true
      tf-environment:
        description: The Terraform environment to deploy to
        type: string
        required: true
      dmsbase:
        description: Whether to deploy the DMSBASE component
        type: boolean
        default: true
        required: false
      api:
        description: Whether to deploy the API component
        type: boolean
        default: true
        required: false
      dsp:
        description: Whether to deploy the DSP component
        type: boolean
        default: true
        required: false
      drs:
        description: Whether to deploy the DRS component
        type: boolean
        default: true
        required: false
      dms:
        description: Whether to deploy the DMS component
        type: boolean
        default: true
        required: false
      release-tag:
        description: The version of the microservices to be deployed
        type: string
        required: false
      disable-cw-event-rules:
        description: Whether to disable the events that interact with the databases before deployment
        type: boolean
        default: false
        required: false
      tf-args:
        description: Additional Terraform arguments
        type: string
        required: false
      full-dms-deploy:
        description: Whether to run a full static load when there are changes to the static task
        type: boolean
        required: true
      tars-replica-db-script-branch:
        description: The branch to run the DB scripts from
        type: string
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  start-ec2-runner:
    name: ▶️ Start EC2 Runner
    uses: dvsa/des-workflow-actions/.github/workflows/manage-gha-tf-runner.yaml@main
    with:
      action: start
    secrets:
      AWS_ACCOUNT_ID: ${{ inputs.aws-account == 'prod' && secrets.AWS_PROD_ACCOUNT_ID || secrets.AWS_NONPROD_ACCOUNT_ID }}
      DVSA_AWS_REGION: ${{ secrets.DVSA_AWS_REGION }}
      GH_TOKEN_TEMP: ${{ secrets.GH_TOKEN_TEMP }}

  stop-dms-tasks:
    name: ⏹️ Stop DMS Tasks
    if: inputs.full-dms-deploy == true
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Assume AWS ${{ inputs.aws-account }} Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-account == 'prod' && secrets.DES_AWS_ROLE_PROD || secrets.DES_AWS_ROLE_NONPROD }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}
          role-session-name: Terraform-GHA

      - name: 🔍 Get DMS Task ARNs
        id: dms-tasks
        run: |
          static_task_arn=$(aws dms describe-replication-tasks --without-settings --region ${{ secrets.DVSA_AWS_REGION }} |
          jq '.ReplicationTasks[] | select(.ReplicationTaskIdentifier |
          test("mes-${{ inputs.tf-environment }}-dms-static-full-load-and-cdc")) | .ReplicationTaskArn' --raw-output)
          echo "static_task_arn=$static_task_arn" >> $GITHUB_OUTPUT
          
          date_filtered_task_arn=$(aws dms describe-replication-tasks --without-settings --region ${{ secrets.DVSA_AWS_REGION }} |
          jq '.ReplicationTasks[] | select(.ReplicationTaskIdentifier |
          test("mes-${{ inputs.tf-environment }}-dms-datefiltered-full-load-and-cdc")) | .ReplicationTaskArn' --raw-output)
          echo "date_filtered_task_arn=$date_filtered_task_arn" >> $GITHUB_OUTPUT
          
          echo "✅ DMS Task ARNs successfully retrieved."

      - name: ⏹️ Stop Static Task
        uses: dvsa/des-workflow-actions/.github/actions/dms-functions/stop-dms-task@main
        with:
          task-arn: ${{ steps.dms-tasks.outputs.static_task_arn }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}

      - name: ⏹️ Stop Date Filtered Task
        uses: dvsa/des-workflow-actions/.github/actions/dms-functions/stop-dms-task@main
        with:
          task-arn: ${{ steps.dms-tasks.outputs.date_filtered_task_arn }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}

  disable-cw-event-rules:
    name: ⏹️ Disable CloudWatch Event Rules
    needs: [start-ec2-runner, stop-dms-tasks]
    if: always() && !failure() && !cancelled() && inputs.disable-cw-event-rules == true
    runs-on: ${{ needs.start-ec2-runner.outputs.runner-label }}
    outputs:
        drs-tf-args: ${{ steps.disable-cw-event-rules.outputs.drs-tf-args }}
        dms-tf-args: ${{ steps.disable-cw-event-rules.outputs.dms-tf-args }}
    steps:
      - name: ⏹️ Disable DRS Pollers
        id: disable-cw-event-rules
        uses: dvsa/des-workflow-actions/.github/actions/aws-functions/manage-cw-event-rules@main
        with:
          branch: ${{ inputs.branch }}
          token: ${{ secrets.GH_TOKEN_TEMP }}
          aws-account: ${{ inputs.aws-account }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}
          tf-environment: ${{ inputs.tf-environment }}
          action: disable
          mgmt-role: ${{ secrets.DES_AWS_ROLE }}
          role-to-assume: ${{ inputs.aws-account == 'prod' && secrets.DES_AWS_ROLE_PROD || secrets.DES_AWS_ROLE_NONPROD }}

  deploy-dmsbase:
    name: 🧩 DMSBASE
    needs: [start-ec2-runner, disable-cw-event-rules]
    if: always() && !failure() && !cancelled() && inputs.tf-environment != 'dev' && inputs.dmsbase == true
    strategy:
      max-parallel: 1
      matrix:
        tf-action: [plan, apply]
    uses: dvsa/des-workflow-actions/.github/workflows/terraform-action.yaml@main
    with:
      runner: ${{ needs.start-ec2-runner.outputs.runner-label }}
      branch: ${{ inputs.branch }}
      aws-account: ${{ inputs.aws-account }}
      tf-environment: ${{ inputs.tf-environment == 'perf' && 'nonprod' || inputs.tf-environment }}
      tf-component: dmsbase
      tf-action: ${{ matrix.tf-action }}
    secrets: inherit

  deploy-api:
    name: 🧩 API
    needs: [start-ec2-runner, deploy-dmsbase]
    if: always() && !failure() && !cancelled() && inputs.api == true
    strategy:
      max-parallel: 1
      matrix:
        tf-action: [plan, apply]
    uses: dvsa/des-workflow-actions/.github/workflows/terraform-action.yaml@main
    with:
      runner: ${{ needs.start-ec2-runner.outputs.runner-label }}
      branch: ${{ inputs.branch }}
      aws-account: ${{ inputs.aws-account }}
      tf-environment: ${{ inputs.tf-environment }}
      tf-component: api
      release-tag: ${{ inputs.release-tag }}
      tf-args: ${{ inputs.tf-args }}
      tf-action: ${{ matrix.tf-action }}
    secrets: inherit

  deploy-dsp:
    name: 🧩 DSP
    needs: [ start-ec2-runner, deploy-api ]
    if: always() && !failure() && !cancelled() && inputs.dsp == true
    strategy:
      max-parallel: 1
      matrix:
        tf-action: [ plan, apply ]
    uses: dvsa/des-workflow-actions/.github/workflows/terraform-action.yaml@main
    with:
      runner: ${{ needs.start-ec2-runner.outputs.runner-label }}
      branch: ${{ inputs.branch }}
      aws-account: ${{ inputs.aws-account }}
      tf-environment: ${{ inputs.tf-environment }}
      tf-component: dsp
      release-tag: ${{ inputs.release-tag }}
      tf-args: ${{ inputs.tf-args }}
      tf-action: ${{ matrix.tf-action }}
    secrets: inherit

  deploy-drs:
    name: 🧩 DRS
    needs: [start-ec2-runner, disable-cw-event-rules, deploy-dsp]
    if: always() && !failure() && !cancelled() && inputs.drs == true
    strategy:
      max-parallel: 1
      matrix:
        tf-action: [plan, apply]
    uses: dvsa/des-workflow-actions/.github/workflows/terraform-action.yaml@main
    with:
      runner: ${{ needs.start-ec2-runner.outputs.runner-label }}
      branch: ${{ inputs.branch }}
      aws-account: ${{ inputs.aws-account }}
      tf-environment: ${{ inputs.tf-environment }}
      tf-component: drs
      release-tag: ${{ inputs.release-tag }}
      tf-args: ${{ needs.disable-cw-event-rules.outputs.drs-tf-args || inputs.tf-args }}
      tf-action: ${{ matrix.tf-action }}
    secrets: inherit

  create-db-users:
    name: ✨ Create DB Users
    needs: [start-ec2-runner, deploy-drs]
    if: always() && !failure() && !cancelled() && inputs.full-dms-deploy == true
    runs-on: ${{ needs.start-ec2-runner.outputs.runner-label }}
    steps:
      - name: 🔑 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-account == 'prod' && secrets.DES_AWS_ROLE_PROD || secrets.DES_AWS_ROLE_NONPROD }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}
          role-session-name: Terraform-GHA

      - name: 🤫 Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: RDS_CREDENTIALS, des-${{ inputs.tf-environment }}-rds-credentials
          parse-json-secrets: true

      - name: ✨ Create DMS User
        uses: dvsa/des-workflow-actions/.github/actions/db-functions/run-db-script@main
        with:
          db-script-repo: dvsa/mes-data-poller-service
          db-script-branch: ${{ inputs.db-script-branch }}
          db-script-path: destination-db/user-creation
          db-cname: ${{ env.RDS_CREDENTIALS_TARS_DB_CNAME }}
          db-username: ${{ env.RDS_CREDENTIALS_TARS_DB_USERNAME }}
          db-password: ${{ env.RDS_CREDENTIALS_TARS_DB_PASSWORD }}
          user-password: ${{ env.RDS_CREDENTIALS_TARS_DMS_USER_PASSWORD }}
          db-script-filename: 010_createDMSUser.sql

      - name: ✨ Create Ref Data User
        uses: dvsa/des-workflow-actions/.github/actions/db-functions/run-db-script@main
        with:
          db-script-repo: dvsa/mes-data-poller-service
          db-script-branch: ${{ inputs.db-script-branch }}
          db-script-path: destination-db/user-creation
          db-cname: ${{ env.RDS_CREDENTIALS_TARS_DB_CNAME }}
          db-username: ${{ env.RDS_CREDENTIALS_TARS_DB_USERNAME }}
          db-password: ${{ env.RDS_CREDENTIALS_TARS_DB_PASSWORD }}
          user-password: ${{ env.RDS_CREDENTIALS_TARS_REFDATA_USER_PASSWORD }}
          db-script-filename: 060_createRefdataUser.sql

  deploy-dms:
    name: 🧩 DMS
    needs: [start-ec2-runner, disable-cw-event-rules, create-db-users]
    if: always() && !failure() && !cancelled() && inputs.dms == true
    strategy:
      max-parallel: 1
      matrix:
        tf-action: [plan, apply]
    uses: dvsa/des-workflow-actions/.github/workflows/terraform-action.yaml@main
    with:
      runner: ${{ needs.start-ec2-runner.outputs.runner-label }}
      branch: ${{ inputs.branch }}
      aws-account: ${{ inputs.aws-account }}
      tf-environment: ${{ inputs.tf-environment }}
      tf-component: dms
      release-tag: ${{ inputs.release-tag }}
      tf-args: ${{ needs.disable-cw-event-rules.outputs.dms-tf-args || inputs.tf-args }}
      tf-action: ${{ matrix.tf-action }}
    secrets: inherit

  full-dms-deploy:
    name: 🚀 Full DMS Deploy
    needs: [start-ec2-runner, deploy-dms]
    if: always() && !failure() && !cancelled() && inputs.full-dms-deploy == true
    uses: dvsa/des-workflow-actions/.github/workflows/full-dms-deploy.yaml@main
    with:
      runner: ${{ needs.start-ec2-runner.outputs.runner-label }}
      aws-account: ${{ inputs.aws-account }}
      tf-environment: ${{ inputs.tf-environment }}
      db-script-branch: ${{ inputs.tars-replica-db-script-branch }}
    secrets: inherit

  enable-cw-event-rules:
    name: ▶️ Enable CloudWatch Event Rules
    needs: [start-ec2-runner, full-dms-deploy]
    if: always() && !failure() && !cancelled() && inputs.disable-cw-event-rules == true
    runs-on: ${{ needs.start-ec2-runner.outputs.runner-label }}
    steps:
      - name: ▶️ Enable CloudWatch Event Rules
        uses: dvsa/des-workflow-actions/.github/actions/aws-functions/manage-cw-event-rules@main
        with:
          branch: ${{ inputs.branch }}
          token: ${{ secrets.GH_TOKEN_TEMP }}
          aws-account: ${{ inputs.aws-account }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}
          tf-environment: ${{ inputs.tf-environment }}
          action: enable
          mgmt-role: ${{ secrets.DES_AWS_ROLE }}
          role-to-assume: ${{ inputs.aws-account == 'prod' && secrets.DES_AWS_ROLE_PROD || secrets.DES_AWS_ROLE_NONPROD }}

  stop-ec2-runner:
    name: ⏹️ Stop EC2 Runner
    needs: [start-ec2-runner, enable-cw-event-rules]
    if: always()
    uses: dvsa/des-workflow-actions/.github/workflows/manage-gha-tf-runner.yaml@main
    with:
      action: stop
      runner-label: ${{ needs.start-ec2-runner.outputs.runner-label }}
      ec2-instance-id: ${{ needs.start-ec2-runner.outputs.ec2-instance-id }}
    secrets:
      AWS_ACCOUNT_ID: ${{ inputs.aws-account == 'prod' && secrets.AWS_PROD_ACCOUNT_ID || secrets.AWS_NONPROD_ACCOUNT_ID }}
      DVSA_AWS_REGION: ${{ secrets.DVSA_AWS_REGION }}
      GH_TOKEN_TEMP: ${{ secrets.GH_TOKEN_TEMP }}
