name: 🚀 Terraform Deploy (Personal Environment)
on:
  workflow_call:
    inputs:
      branch:
        description: The Terraform branch to deploy
        type: string
        required: true
      aws-account:
        description: The AWS account to deploy to
        type: string
        required: true
      tf-environment:
        description: The Terraform environment to deploy to
        type: string
        required: true
      tf-action:
        description: The Terraform action to take (apply/destroy)
        type: string
        required: true
      initialise-results-db:
        description: Whether to initialise the results database
        type: boolean
        default: false
        required: false
      load-dynamodb-test-data:
        description: Whether to load the DynamoDB test data
        type: boolean
        required: false
      dynamodb-test-data-branch:
        description: DynamoDB Test Data Branch
        type: string
        required: false
      disable-cw-event-rules:
        description: Whether to disable the events that interact with the databases before deployment
        type: boolean
        default: false
        required: false

permissions:
  id-token: write
  contents: write

jobs:
  start-ec2-runner:
    name: ▶️ Start EC2 Runner
    uses: dvsa/des-workflow-actions/.github/workflows/manage-gha-tf-runner.yaml@main
    with:
      action: start
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_NONPROD_ACCOUNT_ID }}
      DVSA_AWS_REGION: ${{ secrets.DVSA_AWS_REGION }}
      GH_TOKEN_TEMP: ${{ secrets.GH_TOKEN_TEMP }}

  set-tf-args:
    name: ⚙️ Set Terraform Arguments
    needs: start-ec2-runner
    if: always() && !failure() && !cancelled()
    runs-on: ${{ needs.start-ec2-runner.outputs.runner-label }}
    outputs:
      first-run: ${{ steps.determine-if-deployed.outputs.first-run }}
      api-args: ${{ steps.set-tf-args.outputs.api-args }}
      api-second-run-args: ${{ steps.set-tf-args.outputs.api-second-run-args }}
      tf-plan-action: ${{ steps.set-tf-args.outputs.tf-plan-action }}

    steps:
      - name: 🕵️ Determine if First Run
        id: determine-if-deployed
        run: |
          tag_name="mes-${{ inputs.tf-environment }}-drs/tars_replica_vpc_endpoint_service"
          
          service_name=$(aws ec2 describe-vpc-endpoint-services --region ${{ secrets.DVSA_AWS_REGION }} \
          --query "ServiceDetails[?Tags[?Key=='Name'&&Value=='$tag_name']].ServiceName")
          
          [ "$service_name" == "[]" ] && first_run="true" || first_run="false"
          
          echo "first-run=$first_run" >> $GITHUB_OUTPUT

      - name: ⚙️ Set Terraform Arguments
        id: set-tf-args
        run: |
          tf_plan_action="plan"

          if [ "${{ inputs.tf-action }}" == "apply" ] && [ "${{ steps.determine-if-deployed.outputs.first-run }}" == "true" ]; then
            api_args="-var='first_run=true'"
          
            api_second_run_args="\
            -target=terraform_remote_state.drs \
            -target=aws_iam_policy_document.ref_data_rds_access \
            -target=aws_iam_policy.ref_data_rds_access \
            -target=aws_iam_policy_attachment.ref_data_rds_access \
            -target=aws_vpc_endpoint.tars_replica \
            -target=module.lambda_ref_data_test_centres_get"
          fi
          
          if [ "${{ inputs.tf-action }}" == "destroy" ]; then        
            api_args="\
            -target=terraform_remote_state.drs \
            -target=aws_iam_policy_document.ref_data_rds_access \
            -target=aws_iam_policy.ref_data_rds_access \
            -target=aws_iam_policy_attachment.ref_data_rds_access \
            -target=aws_vpc_endpoint.tars_replica"
          
            api_second_run_args="-var='first_run=true'"
          
            tf_plan_action="plan-destroy"
          fi
          
          echo "api-args=$api_args" >> $GITHUB_OUTPUT
          echo "api-second-run-args=$api_second_run_args" >> $GITHUB_OUTPUT
          echo "tf-plan-action=$tf_plan_action" >> $GITHUB_OUTPUT

  disable-cw-event-rules:
    name: ⏹️ Disable CloudWatch Event Rules
    needs: [start-ec2-runner, set-tf-args]
    if: always() && !failure() && !cancelled() && inputs.disable-cw-event-rules == true && needs.set-tf-args.outputs.first-run == 'false'
    runs-on: ${{ needs.start-ec2-runner.outputs.runner-label }}
    outputs:
      drs-tf-args: ${{ steps.disable-cw-event-rules.outputs.drs-tf-args }}
      dms-tf-args: ${{ steps.disable-cw-event-rules.outputs.dms-tf-args }}
    steps:
      - name: ⏹️ Disable CloudWatch Event Rules
        id: disable-cw-event-rules
        uses: dvsa/des-workflow-actions/.github/actions/aws-functions/manage-cw-event-rules@main
        with:
          aws-account: ${{ inputs.aws-account }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}
          tf-environment: ${{ inputs.tf-environment }}
          action: disable
          mgmt-role: ${{ secrets.DES_AWS_ROLE }}
          role-to-assume: ${{ secrets.DES_AWS_ROLE_NONPROD }}
          personal-environment: true

  clear-s3-bucket-mocks:
    name: 🗑️ Clear DRS Mock TARS Data Bucket
    needs: [start-ec2-runner, disable-cw-event-rules]
    if: always() && !failure() && !cancelled() && inputs.tf-action == 'destroy'
    runs-on: ${{ needs.start-ec2-runner.outputs.runner-label }}
    steps:
      - name: 🔑 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DES_AWS_ROLE_NONPROD }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}
          role-session-name: Terraform-GHA

      - name: 🗑️ Clear DRS Mock TARS Data Bucket
        run: |
          bucket="mes-${{ secrets.AWS_NONPROD_ACCOUNT_ID }}-${{ inputs.tf-environment }}-drs-mock-tars-data"
          s3_objects=$(aws s3 ls s3://${bucket})
          
          if [[ -n "$s3_objects" ]]; then
            object_versions=$(aws s3api list-object-versions --bucket ${bucket} | jq '.Versions + .DeleteMarkers | {Objects: map({Key, VersionId})}')
            aws s3api delete-objects --bucket ${bucket} --delete "${object_versions}"
          fi

  deploy-api:
    name: 🧩 API
    needs: [start-ec2-runner, set-tf-args, clear-s3-bucket-mocks]
    if: always() && !failure() && !cancelled()
    strategy:
      max-parallel: 1
      matrix:
        tf-action: ["${{ needs.set-tf-args.outputs.tf-plan-action }}", "${{ inputs.tf-action }}"]
    uses: dvsa/des-workflow-actions/.github/workflows/terraform-action.yaml@main
    with:
      runner: ${{ needs.start-ec2-runner.outputs.runner-label }}
      branch: ${{ inputs.branch }}
      aws-account: ${{ inputs.aws-account }}
      tf-environment: ${{ inputs.tf-environment }}
      tf-component: api
      tf-args: ${{ needs.set-tf-args.outputs.api-args }}
      tf-action: ${{ matrix.tf-action }}
      artefact-name-prefix: 0
    secrets: inherit

  deploy-dsp:
    name: 🧩 DSP
    needs: [start-ec2-runner, set-tf-args, deploy-api]
    if: always() && !failure() && !cancelled()
    strategy:
      max-parallel: 1
      matrix:
        tf-action: ["${{ needs.set-tf-args.outputs.tf-plan-action }}", "${{ inputs.tf-action }}"]
    uses: dvsa/des-workflow-actions/.github/workflows/terraform-action.yaml@main
    with:
      runner: ${{ needs.start-ec2-runner.outputs.runner-label }}
      branch: ${{ inputs.branch }}
      aws-account: ${{ inputs.aws-account }}
      tf-environment: ${{ inputs.tf-environment }}
      tf-component: dsp
      tf-args: ${{ inputs.tf-args }}
      tf-action: ${{ matrix.tf-action }}
      artefact-name-prefix: 1
    secrets: inherit

  deploy-drs:
    name: 🧩 DRS
    needs: [start-ec2-runner, set-tf-args, deploy-dsp, disable-cw-event-rules]
    if: always() && !failure() && !cancelled()
    strategy:
      max-parallel: 1
      matrix:
        tf-action: ["${{ needs.set-tf-args.outputs.tf-plan-action }}", "${{ inputs.tf-action }}"]
    uses: dvsa/des-workflow-actions/.github/workflows/terraform-action.yaml@main
    with:
      runner: ${{ needs.start-ec2-runner.outputs.runner-label }}
      branch: ${{ inputs.branch }}
      aws-account: ${{ inputs.aws-account }}
      tf-environment: ${{ inputs.tf-environment }}
      tf-component: drs
      tf-args: ${{ needs.disable-cw-event-rules.outputs.drs-tf-args || inputs.tf-args }}
      tf-action: ${{ matrix.tf-action }}
      artefact-name-prefix: 2
    secrets: inherit

  deploy-api-2nd-run:
    name: 🧩 API 2nd Run
    needs: [start-ec2-runner, set-tf-args, deploy-drs]
    if: always() && !failure() && !cancelled() && (needs.set-tf-args.outputs.first-run == 'true' || inputs.tf-action == 'destroy')
    strategy:
      max-parallel: 1
      matrix:
        tf-action: ["${{ needs.set-tf-args.outputs.tf-plan-action }}", "${{ inputs.tf-action }}"]
    uses: dvsa/des-workflow-actions/.github/workflows/terraform-action.yaml@main
    with:
      runner: ${{ needs.start-ec2-runner.outputs.runner-label }}
      branch: ${{ inputs.branch }}
      aws-account: ${{ inputs.aws-account }}
      tf-environment: ${{ inputs.tf-environment }}
      tf-component: api
      tf-args: ${{ needs.set-tf-args.outputs.api-second-run-args }}
      tf-action: ${{ matrix.tf-action }}
      artefact-name-prefix: 3
    secrets: inherit

  delete-log-groups:
    name: 🗑️ Delete Log Groups
    needs: [start-ec2-runner, deploy-api-2nd-run]
    if: always() && !failure() && !cancelled() && inputs.tf-action == 'destroy'
    runs-on: ${{ needs.start-ec2-runner.outputs.runner-label }}
    steps:
      - name: 🔑 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DES_AWS_ROLE_NONPROD }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}
          role-session-name: Terraform-GHA

      - name: 🗑️ Delete Log Groups
        run: |
          aws logs delete-log-group --log-group-name /aws/rds/cluster/mes-${{ inputs.tf-environment }}-api-mes-db/error \
          --region ${{ secrets.DVSA_AWS_REGION }}
          aws logs delete-log-group --log-group-name /aws/rds/cluster/mes-${{ inputs.tf-environment }}-drs-tars-replica/error \
          --region ${{ secrets.DVSA_AWS_REGION }}

  initialise-results-db:
    name: ✨ Initialise Results & TARS Replica Databases
    needs: [start-ec2-runner, delete-log-groups]
    if: always() && !failure() && !cancelled() && inputs.initialise-results-db == true && inputs.tf-action == 'apply'
    runs-on: ${{ needs.start-ec2-runner.outputs.runner-label }}
    steps:
      - name: 🔑 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DES_AWS_ROLE_NONPROD }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}
          role-session-name: Terraform-GHA

      - name: 🤫 Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: RDS_CREDENTIALS, des-personal-rds-credentials
          parse-json-secrets: true

      - name: ✨ Initialise Results DB
        uses: dvsa/des-workflow-actions/.github/actions/db-functions/run-db-script@main
        with:
          db-script-repo: dvsa/des-results-db
          db-script-branch: master
          token: ${{ secrets.GH_TOKEN_TEMP }}
          db-script-path: database-setup
          db-cname: mes-db.api.${{ inputs.tf-environment }}.${{ env.RDS_CREDENTIALS_PERSONAL_DB_CNAME_SUFFIX }}
          db-username: mes${{ inputs.tf-environment }}${{ env.RDS_CREDENTIALS_PERSONAL_DB_USERNAME_SUFFIX }}
          db-password: ${{ env.RDS_CREDENTIALS_RESULTS_DB_PASSWORD }}

      - name: ✨ Create Results User
        uses: dvsa/des-workflow-actions/.github/actions/db-functions/run-db-script@main
        with:
          db-script-repo: dvsa/des-results-db
          db-script-branch: master
          token: ${{ secrets.GH_TOKEN_TEMP }}
          db-script-path: user-creation
          db-cname: mes-db.api.${{ inputs.tf-environment }}.${{ env.RDS_CREDENTIALS_PERSONAL_DB_CNAME_SUFFIX }}
          db-username: mes${{ inputs.tf-environment }}${{ env.RDS_CREDENTIALS_PERSONAL_DB_USERNAME_SUFFIX }}
          db-password: ${{ env.RDS_CREDENTIALS_RESULTS_DB_PASSWORD }}

      - name: ✨ Create Scheduling Schema and User
        uses: dvsa/des-workflow-actions/.github/actions/db-functions/run-db-script@main
        with:
          db-script-repo: dvsa/des-booking-ingestion-service
          db-script-branch: main
          token: ${{ secrets.GH_TOKEN_TEMP }}
          db-script-path: destination-db/database-objects
          db-cname: mes-db.api.${{ inputs.tf-environment }}.${{ env.RDS_CREDENTIALS_PERSONAL_DB_CNAME_SUFFIX }}
          db-username: mes${{ inputs.tf-environment }}${{ env.RDS_CREDENTIALS_PERSONAL_DB_USERNAME_SUFFIX }}
          db-password: ${{ env.RDS_CREDENTIALS_RESULTS_DB_PASSWORD }}

      - name: 🔄 Initialise TARS Replica
        uses: dvsa/des-workflow-actions/.github/actions/db-functions/run-db-script@main
        with:
          db-script-repo: dvsa/mes-data-poller-service
          db-script-branch: develop
          db-script-path: destination-db/database-initialisation
          db-cname: ${{ inputs.tf-environment }}-db.api.${{ inputs.tf-environment }}.${{ env.RDS_CREDENTIALS_PERSONAL_DB_CNAME_SUFFIX }}
          db-username: mes${{ inputs.tf-environment }}${{ env.RDS_CREDENTIALS_PERSONAL_DB_USERNAME_SUFFIX }}
          db-password: ${{ env.RDS_CREDENTIALS_TARS_DB_PASSWORD }}

      - name: ⏳ Load TARS Replica Database Objects
        uses: dvsa/des-workflow-actions/.github/actions/db-functions/run-db-script@main
        with:
          db-script-repo: dvsa/mes-data-poller-service
          db-script-branch: MES-9843-tf-personal-env-fix
          db-script-path: destination-db/database-objects
          db-cname: ${{ inputs.tf-environment }}-db.api.${{ inputs.tf-environment }}.${{ env.RDS_CREDENTIALS_PERSONAL_DB_CNAME_SUFFIX }}
          db-username: mes${{ inputs.tf-environment }}${{ env.RDS_CREDENTIALS_PERSONAL_DB_USERNAME_SUFFIX }}
          db-password: ${{ env.RDS_CREDENTIALS_TARS_DB_PASSWORD }}

      - name: ✨ Create Ref Data User
        uses: dvsa/des-workflow-actions/.github/actions/db-functions/run-db-script@main
        with:
          db-script-repo: dvsa/mes-data-poller-service
          db-script-branch: MES-9843-tf-personal-env-fix
          db-script-path: destination-db/user-creation
          db-cname: ${{ inputs.tf-environment }}-db.api.${{ inputs.tf-environment }}.${{ env.RDS_CREDENTIALS_PERSONAL_DB_CNAME_SUFFIX }}
          db-username: mes${{ inputs.tf-environment }}${{ env.RDS_CREDENTIALS_PERSONAL_DB_USERNAME_SUFFIX }}
          db-password: ${{ env.RDS_CREDENTIALS_TARS_DB_PASSWORD }}
          user-password: ${{ env.RDS_CREDENTIALS_TARS_REFDATA_USER_PASSWORD }}
          db-script-filename: 060_createRefdataUser.sql

  load-test-data:
    name: ⏳ Load Journals & Users Test Data
    needs: [start-ec2-runner, initialise-results-db]
    if: always() && !failure() && !cancelled() && inputs.load-dynamodb-test-data == true && inputs.tf-action == 'apply'
    runs-on: ${{ needs.start-ec2-runner.outputs.runner-label }}
    steps:
      - name: 📨 Checkout Test Data Repository
        uses: actions/checkout@v4
        with:
          repository: dvsa/des-test-data-journal
          ref: ${{ inputs.dynamodb-test-data-branch }}
          token: ${{ secrets.GH_TOKEN_TEMP }}

      - name: ➕ Install Pip
        run: sudo dnf install python3-pip -y

      - name: ➕ Install Requirements
        run: python3 -m pip install -r requirements.txt --user

      - name: 🔑 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DES_AWS_ROLE_NONPROD }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}
          role-session-name: Terraform-GHA

      - name: ⏳ Load Tables
        env:
          S3_MOCK_DATA_BUCKET: mes-${{ secrets.AWS_NONPROD_ACCOUNT_ID }}-${{ inputs.tf-environment }}-drs-mock-tars-data
        run: |
          python3 ./load_test_user_data.py ${{ inputs.tf-environment }}
          python3 ./load_test_journal_data.py ${{ inputs.tf-environment }}

  enable-cw-event-rules:
    name: ▶️ Enable CloudWatch Event Rules
    needs: [start-ec2-runner, load-test-data]
    if: always() && !failure() && !cancelled() && inputs.disable-cw-event-rules == true && needs.set-tf-args.outputs.first-run == 'false'
    runs-on: ${{ needs.start-ec2-runner.outputs.runner-label }}
    steps:
      - name: ▶️ Enable CloudWatch Event Rules
        uses: dvsa/des-workflow-actions/.github/actions/aws-functions/manage-cw-event-rules@main
        with:
          aws-account: ${{ inputs.aws-account }}
          aws-region: ${{ secrets.DVSA_AWS_REGION }}
          tf-environment: ${{ inputs.tf-environment }}
          action: enable
          mgmt-role: ${{ secrets.DES_AWS_ROLE }}
          role-to-assume: ${{ secrets.DES_AWS_ROLE_NONPROD }}
          personal-environment: true

  stop-ec2-runner:
    name: ⏹️ Stop EC2 Runner
    needs: [start-ec2-runner, enable-cw-event-rules]
    if: always()
    uses: dvsa/des-workflow-actions/.github/workflows/manage-gha-tf-runner.yaml@main
    with:
      action: stop
      runner-label: ${{ needs.start-ec2-runner.outputs.runner-label }}
      ec2-instance-id: ${{ needs.start-ec2-runner.outputs.ec2-instance-id }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_NONPROD_ACCOUNT_ID }}
      DVSA_AWS_REGION: ${{ secrets.DVSA_AWS_REGION }}
      GH_TOKEN_TEMP: ${{ secrets.GH_TOKEN_TEMP }}
